name: logistics-oracle
services:

  oracle-db:
    image: gvenzl/oracle-free:23

    container_name: logistics-oracle

    restart: always

    environment:
      ORACLE_PASSWORD: oracle

    ports:
      - "1522:1521"

    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data: